apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-backend-deployment
  labels:
    app: gateway-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-backend
  template:
    metadata:
      labels:
        app: gateway-backend
    spec:
      containers:
        - name: gateway-backend
          image: okteto.dev/gateway
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: gateway-postgres-config
            - configMapRef:
                name: gateway-backend-config
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: auth-secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: aws-secret-access-key
            - name: INITIAL_SERVICES
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: initial-services
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            limits:
              memory: "3Gi"
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-backend-service
spec:
  selector:
    app: gateway-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
