"""init

Revision ID: 981ecd6fab71
Revises:
Create Date: 2023-06-03 22:33:33.718533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "981ecd6fab71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=31), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("apikey_hash", sa.LargeBinary(length=64), nullable=False),
        sa.Column("apikey_salt", sa.LargeBinary(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_services_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_services_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_services_name"))
        batch_op.drop_index(batch_op.f("ix_services_id"))

    op.drop_table("services")
    # ### end Alembic commands ###
