"""add tokens

Revision ID: fabcd5b40cb4
Revises: 981ecd6fab71
Create Date: 2023-06-04 01:50:37.920211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fabcd5b40cb4"
down_revision = "981ecd6fab71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sa.Integer(), nullable=False),
        sa.Column("iat", sa.Integer(), nullable=False),
        sa.Column("exp", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tokens_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tokens_sub"), ["sub"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_sub"))
        batch_op.drop_index(batch_op.f("ix_tokens_id"))

    op.drop_table("tokens")
    # ### end Alembic commands ###
